USE master

DROP DATABASE IF EXISTS DBVENTA

CREATE DATABASE DBVENTA
GO

USE DBVENTA
GO


--1FN--
CREATE TABLE CLIENTE
(IdCliente INT IDENTITY(1,1) NOT NULL,
 Nombre VARCHAR(50) NOT NULL,
 APaterno VARCHAR(50) NOT NULL,
 AMaterno VARCHAR(50) NOT NULL,
 DNI CHAR(10) NOT NULL,
 Direccion VARCHAR(250) NOT NULL,
 FecNac DATE NOT NULL,
 IsActivo BIT NOT NULL
 CONSTRAINT DF_IsActivo_CLI DEFAULT(1),
 FecRegistro DATE
 CONSTRAINT DF_FecRegistro_CLI DEFAULT(GETDATE()),
 CONSTRAINT PK_IdCliente_CLI PRIMARY KEY(IdCliente))
 GO

CREATE TABLE PROVEEDOR
(IdProveedor INT IDENTITY(1,1) NOT NULL,
 Nombre VARCHAR(50) NOT NULL,
 NIF CHAR(10) NOT NULL,
 Direccion VARCHAR(250) NOT NULL,
 IsActivo BIT NOT NULL
 CONSTRAINT DF_IsActivo_PRO DEFAULT(1),
 FecRegistro DATE
 CONSTRAINT DF_FecRegistro_PRO DEFAULT(GETDATE()),
 CONSTRAINT PK_IdProveedor_PRO PRIMARY KEY (IdProveedor))
 GO

 --2FN--
CREATE TABLE PRODUCTO
(IdProducto INT IDENTITY(1,1) NOT NULL,
 PLU VARCHAR(6) NOT NULL,
 Nombre VARCHAR(40) NOT NULL,
 PUnitario DECIMAL(12,2) NOT NULL,
 IdProveedor INT NOT NULL,
 IsActivo BIT NOT NULL
 CONSTRAINT DF_IsActivo_PRD DEFAULT(1),
 FecRegistro DATE
 CONSTRAINT DF_FecRegistro_PRD DEFAULT(GETDATE()),
 CONSTRAINT PK_IdProducto_PRD PRIMARY KEY (IdProducto),
 CONSTRAINT FK_IdProveedor_PRD FOREIGN KEY (IdProveedor) REFERENCES PROVEEDOR (IdProveedor))
 GO

CREATE TABLE VENTA
(IdVenta INT NOT NULL,
IdCliente INT NOT NULL,
FecVenta DATETIME NOT NULL
CONSTRAINT DF_FecVenta_VEN DEFAULT(GETDATE()),
CONSTRAINT PK_IdVenta_VEN PRIMARY KEY (IdVenta),
CONSTRAINT FK_IdCliente_VEN FOREIGN KEY (IdCliente) REFERENCES CLIENTE (IdCliente))
GO

CREATE TABLE VENTA_DETALLE
(IdVenta INT NOT NULL,
 IdProducto INT NOT NULL,
 PUnitario DECIMAL(12,2) NOT NULL,
 Cantidad SMALLINT NOT NULL,
 CONSTRAINT FK_IdVenta_VED FOREIGN KEY (IdVenta) REFERENCES VENTA(IdVenta) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT FK_IdProducto_VED FOREIGN KEY (IdProducto) REFERENCES PRODUCTO(IdProducto))
GO
